### ISSUE TITLE
Require signed certificate on Click Once publish

### ISSUE THREAD

**Issue by lawrence910426** [dinnersystem/Factory-Frontend#2]
It won't cause any damage, but it would be better if we could sign it.

**Comment by lawrence910426** [comment]
It's not essential to sign a certificate, but if you don't sign the certificate there will be annoying security announcements everywhere.

**Comment by seanpai96** [comment]
code-signing certificate is hella expensive and definitely not worth the price

**Comment by lawrence910426** [comment]
Then let's close this issue ><
